[package]
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
edition = "2018"
name = "webwire-cli"
description = "Contract-First API System - Command Line Interface"
homepage = "https://webwire.dev/"
version = "0.1.0"

[dependencies]
clap = "2.33"
nom = "6.0"
nom_locate = "3.0"
proc-macro2 = "1.0"
quote = "1.0"
